### ISSUE TITLE
popup seeport

### ISSUE THREAD

**Issue by SilviaVernelli** [mauriziocingolani/yii_fmwk_php#1]
Ciao Maurizio,
potresti mettere il nuovo pop-up sul sito del SeePort? Il testo è questo:

"Torna sabato 28 febbraio il Saturday Seeport Night con un imperdibile secondo appuntamento!

Il Ginevra Resturant è pronto per stupirvi di nuovo con il menù Mediterranean Fusion.

Grecia, Spagna, Italia, Turchia e Marocco: sono solo alcune delle terre che si incontrano in questa cena speziata e inebriante, per un viaggio tra odori, sapori e tradizioni millenarie.

Un dj set dal vivo vi accompagnerà in questa esperienza unica, che vi farà scoprire tutte le sfumature del Mediterraneo.

Prenota subito chiamando lo 071.9715101 o scrivendo a info@seeporthotel.com!

Per maggiori info: bit.ly/MediterraneanFusion"

![mediterranean-def-01](https://cloud.githubusercontent.com/assets/10738335/6329275/1e701fa0-bb6f-11e4-92c6-9311f899efbb.jpg)

Grazie!

Silvia

**Comment by mauriziocingolani** [comment]
Ho messo il popup con l’immagine e un po’ di testo sotto, vedete se va bene.
In alternativa si può tagliare il testo dall’immagine e riscriverlo sotto.
Per inglese-tedesco-russo?

Attendo istruzioni.
Ciao

PS @silvia Per favore le issue aprile sul repository del seeport: https://github.com/mauriziocingolani/seeport/issues (questa l’hai aperta su un altro progetto)
[logo_ggf]

Maurizio Cingolani
Servizi Informatici

via Albertini, 36
Gross Ancona Blocco I1
60131 Ancona

t +39 071 2850
f +39 071 2869888
skype mauriziocingolani

[http://www.sidagroup.com/template/upload/1270804506logo%20albero%20mail.jpg]   Rispetta l'ambiente: se non ti è necessario, non stampare questa email.
Please consider the environment before printing this email.
INFORMATIVA AI SENSI DEL D.LGS.196/03
Le informazioni contenute nella presente e-mail e negli eventuali allegati sono riservate e devono essere nella disponibilità del solo destinatario. Se avete ricevuto per errore questa e-mail siete pregati di informarci e di provvedere alla sua rimozione. Chiunque venga in possesso senza alcuna autorizzazione di questa e-mail è vincolato dalla legge a non leggerne il contenuto, a non copiarla, a non diffonderla e a non utilizzarla per scopi personali. La informiamo che per l'esercizio dei diritti di cui all'art. 7 del D. Lgs. 196/2003 può rivolgersi al titolare del trattamento dati GGF Group.
CONFIDENTIALITY NOTICE
This message and its attachments are addressed solely to the persons above and may contain confidential information. If you have received the message in error, be informed that any use of the content here of is prohibited. Please return it immediately to the sender and delete the message. Should you have any questions, please contact us by replying to info@ggfgroup.itmailto:info@ggfgroup.it. Thank you.

Il giorno 23/feb/2015, alle ore 15:20, SilviaVernelli <notifications@github.com<mailto:notifications@github.com>> ha scritto:

Ciao Maurizio,
potresti mettere il nuovo pop-up sul sito del SeePort? Il testo è questo:

"Torna sabato 28 febbraio il Saturday Seeport Night con un imperdibile secondo appuntamento!

Il Ginevra Resturant è pronto per stupirvi di nuovo con il menù Mediterranean Fusion.

Grecia, Spagna, Italia, Turchia e Marocco: sono solo alcune delle terre che si incontrano in questa cena speziata e inebriante, per un viaggio tra odori, sapori e tradizioni millenarie.

Un dj set dal vivo vi accompagnerà in questa esperienza unica, che vi farà scoprire tutte le sfumature del Mediterraneo.

Prenota subito chiamando lo 071.9715101 o scrivendo a info@seeporthotel.commailto:info@seeporthotel.com!

Per maggiori info: bit.ly/MediterraneanFusionhttp://bit.ly/MediterraneanFusion"

[mediterranean-def-01]

Grazie!

Silvia
